export const palette = {
  primary: '#8BCFD7',
  primaryDark: '#397F88',
  accent: '#B9DDAF',
  accentDark: '#3C704A',
  background: '#F8FAF9',
  backgroundDark: '#172321',
  card: '#EEF3F1',
  cardDark: '#243330',
  cardElevated: '#FFFFFF',
  cardElevatedDark: '#293936',
  text: '#202D2B',
  textDark: '#F1F6F3',
  subtitle: '#65736E',
  subtitleDark: '#ACBDB6',
  border: '#E4ECE8',
  borderDark: '#3A4D47',
  error: '#B55352',
  warning: '#86652F',
  purple: '#6C6193',
  pink: '#985D70',
  mintSurface: '#DDEFCF',
  lemonSurface: '#FFF2AC',
  aquaSurface: '#DDF1F2',
  lavenderSurface: '#EAE6F5',
  peachSurface: '#F8E8DE',
  google: '#4285F4',
  googleDark: '#3367D6',
} as const;

export function getTheme(isDark: boolean) {
  return {
    background: isDark ? palette.backgroundDark : palette.background,
    card: isDark ? palette.cardDark : palette.card,
    cardElevated: isDark ? palette.cardElevatedDark : palette.cardElevated,
    text: isDark ? palette.textDark : palette.text,
    subtitle: isDark ? palette.subtitleDark : palette.subtitle,
    border: isDark ? palette.borderDark : palette.border,
  };
}
